#!/usr/bin/env python3
"""
Lab Members Data Generator
This script reads markdown files from people/ directory and generates members-data.js
"""

import os
import re
from pathlib import Path

def parse_yaml_frontmatter(content):
    """Parse YAML front matter from markdown content"""
    match = re.match(r'^---\s*\n(.*?)\n---', content, re.DOTALL)
    if not match:
        return None
    
    yaml_content = match.group(1)
    data = {}
    
    for line in yaml_content.split('\n'):
        if ':' in line:
            key, value = line.split(':', 1)
            key = key.strip()
            value = value.strip()
            data[key] = value
    
    return data

def categorize_member(member_data):
    """Categorize member based on their title"""
    if member_data.get('alumni', '').lower() == 'true':
        return 'alumni'

    title = member_data.get('title', '').lower()

    if 'ph.d' in title or 'phd' in title:
        return 'phd_students'
    elif 'master' in title:
        return 'master_students'
    elif 'intern' in title or 'assistant' in title:
        return 'research_interns'
    elif 'visiting' in title or 'visitor' in title:
        return 'visiting_scholars'
    else:
        return 'other'

def format_member_object(data, indent=8):
    """Format member data as JavaScript object"""
    spaces = ' ' * indent
    lines = ['{']
    
    # Add fields in order
    fields = ['name', 'title', 'period', 'co_supervised', 'intern', 'affiliation',
              'photo', 'homepage', 'google_scholar', 'email', 'github', 'alumni']
    
    for field in fields:
        if field in data and data[field]:
            value = data[field]
            lines.append(f'{spaces}    {field}: "{value}",')
    
    # Remove trailing comma from last line
    if len(lines) > 1 and lines[-1].endswith(','):
        lines[-1] = lines[-1][:-1]
    
    lines.append(f'{spaces}}}')
    return '\n'.join(lines)

def generate_members_data_js():
    """Generate members-data.js from markdown files"""
    people_dir = Path('people')
    
    # Categories for organizing members
    categories = {
        'phd_students': [],
        'master_students': [],
        'research_interns': [],
        'visiting_scholars': [],
        'alumni': [],
        'other': []
    }
    
    # Read all markdown files
    for md_file in people_dir.glob('*.md'):
        # Skip documentation files
        if md_file.name.lower() in ['readme.md', 'how_to_add_member.md']:
            continue
        
        try:
            content = md_file.read_text(encoding='utf-8')
            member_data = parse_yaml_frontmatter(content)
            
            if member_data:
                category = categorize_member(member_data)
                categories[category].append(member_data)
                print(f"✓ Processed: {md_file.name} -> {category}")
            else:
                print(f"⚠ Warning: No YAML front matter found in {md_file.name}")
        except Exception as e:
            print(f"✗ Error processing {md_file.name}: {e}")
    
    # Sort members by order field (if exists)
    for category in categories:
        categories[category].sort(key=lambda x: int(x.get('order', 999)))
    
    # Generate JavaScript file
    js_content = """// Lab Members Data
// This file is AUTO-GENERATED by generate_members_data.py
// DO NOT EDIT MANUALLY - Edit markdown files in people/ directory instead
// To regenerate: python generate_members_data.py

const labMembers = {
    director: {
        name: "Yueming Lyu",
        title: "Assistant Professor / Specially Appointed Researcher",
        affiliation: "School of Intelligence Science and Technology, Nanjing University",
        period: "2024 ~ Present",
        photo: "./assets/img/yueming-profile.jpg",
        bio: "Prof. Yueming Lyu is an Assistant Professor, Specially Appointed Researcher, and Ph.D. Supervisor at the School of Intelligence Science and Technology, Nanjing University. Her research focuses on generative AI, agent systems, AI safety, and multimedia forensics.",
        homepage: "./index.html",
        google_scholar: "https://scholar.google.com/citations?user=TxuK84wAAAAJ",
        email: "ymlv@nju.edu.cn",
        github: "https://github.com/Yueming6568"
    },
    
"""
    
    # Add each category
    for category, members in categories.items():
        if category == 'other' or not members:
            continue
        
        js_content += f"    {category}: [\n"
        for i, member in enumerate(members):
            js_content += format_member_object(member)
            if i < len(members) - 1:
                js_content += ','
            js_content += '\n'
        js_content += "    ],\n    \n"
    
    js_content += "};\n"
    
    # Write to file
    output_file = Path('assets/js/members-data.js')
    output_file.write_text(js_content, encoding='utf-8')
    print(f"\n✓ Generated: {output_file}")
    
    # Print statistics
    total = sum(len(members) for cat, members in categories.items() if cat != 'other')
    print(f"\n📊 Statistics:")
    for category, members in categories.items():
        if category != 'other' and members:
            print(f"   - {category}: {len(members)} member(s)")
    print(f"   Total: {total} member(s)")

if __name__ == '__main__':
    print("🔄 Generating members-data.js from markdown files...\n")
    generate_members_data_js()
    print("\n✅ Done!")
